"use client";

import { useMemo, useState } from "react";
import {
  Activity,
  Check,
  CheckCircle2,
  Copy,
  Eye,
  EyeOff,
  Gauge,
  Loader2,
  RefreshCw,
  Wrench,
  XCircle
} from "lucide-react";
import { ConfirmDialog } from "@/components/ui/ConfirmDialog";
import { SectionKicker } from "@/components/ui/SectionKicker";
import { useToast } from "@/components/ui/Toast";
import { useDemoSession } from "@/lib/demo-session";

const DEMO_INGEST_URL = "rtmp://ingest.demo.thearcade.tv/live";
const DEMO_STREAM_KEY_PREFIX = "arcade_demo_";

function randomKey() {
  return `${DEMO_STREAM_KEY_PREFIX}${Math.random().toString(36).slice(2, 10)}_${Math.random().toString(36).slice(2, 10)}`;
}

type TestState = "idle" | "testing" | "success" | "failed";
type Software = "obs" | "streamlabs";

interface TestError {
  title: string;
  explanation: string;
  fix: string;
}

const TEST_ERRORS: TestError[] = [
  {
    title: "Connection timed out",
    explanation: "Your encoder couldn't reach the ingest server within 8 seconds — usually a firewall or VPN blocking outbound RTMP traffic on port 1935.",
    fix: "Temporarily disable any VPN and check that your firewall allows outbound connections on port 1935, then retry."
  },
  {
    title: "Authentication rejected",
    explanation: "The ingest server didn't recognize the stream key it received — often a stray space pasted alongside the key, or an old key still cached in your encoder.",
    fix: "Re-copy the stream key with the button above and paste it fresh into your encoder's Stream Key field, then retry."
  },
  {
    title: "Upload bandwidth insufficient",
    explanation: "Your connection couldn't sustain the bitrate your encoder is set to send, causing the handshake to drop.",
    fix: "Lower your video bitrate to match your measured upload speed below, or close other apps using bandwidth, then retry."
  }
];

function recommendedBitrateKbps(uploadMbps: number): number {
  const budget = Math.round(uploadMbps * 1000 * 0.7);
  return Math.min(8500, Math.max(1500, budget));
}

function recommendedProfile(uploadMbps: number): { resolution: string; fps: string } {
  if (uploadMbps < 5) return { resolution: "1280×720", fps: "30 fps" };
  if (uploadMbps < 10) return { resolution: "1920×1080", fps: "30 fps" };
  return { resolution: "1920×1080", fps: "60 fps" };
}

export default function StreamSetupPage() {
  const { creator } = useDemoSession();
  const { push } = useToast();
  const [step, setStep] = useState(1);
  const [software, setSoftware] = useState<Software | null>(null);
  const [streamKey, setStreamKey] = useState(() => randomKey());
  const [visible, setVisible] = useState(false);
  const [resetConfirmOpen, setResetConfirmOpen] = useState(false);
  const [uploadMbps, setUploadMbps] = useState(12);
  const [testState, setTestState] = useState<TestState>("idle");
  const [testError, setTestError] = useState<TestError | null>(null);

  const bitrate = useMemo(() => recommendedBitrateKbps(uploadMbps), [uploadMbps]);
  const profile = useMemo(() => recommendedProfile(uploadMbps), [uploadMbps]);

  if (!creator) return null;

  function copy(value: string, label: string) {
    navigator.clipboard
      .writeText(value)
      .then(() => push({ kind: "success", title: `${label} copied` }))
      .catch(() => push({ kind: "warning", title: "Couldn't copy", description: "Copy it manually instead." }));
  }

  function runTest() {
    setTestState("testing");
    setTestError(null);
    window.setTimeout(() => {
      const ok = Math.random() > 0.3;
      if (ok) {
        setTestState("success");
      } else {
        setTestState("failed");
        setTestError(TEST_ERRORS[Math.floor(Math.random() * TEST_ERRORS.length)]);
      }
    }, 1400);
  }

  const steps = [
    { id: 1, label: "Your software" },
    { id: 2, label: "Ingest credentials" },
    { id: 3, label: "Recommended settings" },
    { id: 4, label: "Test connection" }
  ];
  const maxUnlockedStep = software ? 4 : 1;

  return (
    <div className="space-y-6">
      <div>
        <SectionKicker>GO-LIVE WIZARD</SectionKicker>
        <h1 className="text-xl font-semibold text-ink">Stream Setup</h1>
        <p className="mt-1 text-sm text-ink-muted">A guided walkthrough to connect OBS Studio or Streamlabs Desktop to The Arcade.</p>
      </div>

      <div className="rounded-lg border border-amber-400/30 bg-amber-400/[0.06] p-4 text-sm text-ink-muted">
        These are demo credentials for this prototype — not a live ingest endpoint. In production, this screen is generated by a real video
        provider, and OBS never talks to a normal webpage directly: it streams RTMP/SRT to that provider's ingest servers.
      </div>

      <div className="flex flex-wrap gap-1 overflow-x-auto rounded-lg border border-surface-border bg-surface-raised p-1.5">
        {steps.map((s) => (
          <button
            key={s.id}
            onClick={() => s.id <= maxUnlockedStep && setStep(s.id)}
            disabled={s.id > maxUnlockedStep}
            aria-current={step === s.id ? "step" : undefined}
            className={`focus-ring flex shrink-0 items-center gap-1.5 rounded-md px-3 py-2 text-xs font-semibold ${
              step === s.id
                ? "bg-brand-magenta/15 text-brand-magenta"
                : s.id < step || s.id <= maxUnlockedStep
                  ? "text-ink-muted hover:bg-surface-panel2 hover:text-ink"
                  : "cursor-not-allowed text-ink-faint/50"
            }`}
          >
            <span className={`flex h-4 w-4 items-center justify-center rounded-full text-[10px] ${step > s.id || (s.id === 1 && software) ? "bg-brand-cyan text-surface" : "bg-surface-panel2"}`}>
              {s.id < step || (s.id === 1 && software) ? <Check size={10} /> : s.id}
            </span>
            {s.label}
          </button>
        ))}
      </div>

      {step === 1 && (
        <div className="rounded-lg border border-surface-border bg-surface-panel p-5">
          <h2 className="mb-3 text-sm font-semibold text-ink">Which broadcasting software do you use?</h2>
          <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
            {(
              [
                { id: "obs" as const, label: "OBS Studio", blurb: "Free, open-source, most widely used." },
                { id: "streamlabs" as const, label: "Streamlabs Desktop", blurb: "OBS-based with built-in alerts and themes." }
              ]
            ).map((opt) => (
              <button
                key={opt.id}
                onClick={() => {
                  setSoftware(opt.id);
                  setStep(2);
                }}
                className={`focus-ring rounded-lg border-2 p-4 text-left transition ${
                  software === opt.id ? "border-brand-magenta bg-brand-magenta/[0.06]" : "border-surface-border hover:border-surface-borderStrong"
                }`}
              >
                <p className="text-sm font-semibold text-ink">{opt.label}</p>
                <p className="mt-1 text-xs text-ink-muted">{opt.blurb}</p>
              </button>
            ))}
          </div>
        </div>
      )}

      {step === 2 && software && (
        <div className="space-y-4">
          <div className="rounded-lg border border-surface-border bg-surface-panel p-5">
            <h2 className="mb-3 text-sm font-semibold text-ink">Your ingest credentials</h2>
            <div className="space-y-3">
              <CopyField label="Server (RTMP URL)" value={DEMO_INGEST_URL} onCopy={() => copy(DEMO_INGEST_URL, "Server URL")} />
              <div>
                <p className="mb-1 text-xs font-medium text-ink-muted">Stream key — private, never share this</p>
                <div className="flex items-center gap-1.5">
                  <code className="flex-1 truncate rounded-md border border-surface-border bg-surface-raised px-3 py-2 text-sm text-ink">
                    {visible ? streamKey : "•".repeat(28)}
                  </code>
                  <button onClick={() => setVisible((v) => !v)} aria-label={visible ? "Hide stream key" : "Show stream key"} className="focus-ring rounded-md border border-surface-border p-2 text-ink-muted hover:text-ink">
                    {visible ? <EyeOff size={15} /> : <Eye size={15} />}
                  </button>
                  <button onClick={() => copy(streamKey, "Stream key")} aria-label="Copy stream key" className="focus-ring rounded-md border border-surface-border p-2 text-ink-muted hover:text-ink">
                    <Copy size={15} />
                  </button>
                </div>
                <p className="mt-1 text-xs text-brand-red">Anyone with this key can broadcast as you. Never paste it in chat, on stream, or in a support ticket screenshot.</p>
              </div>
              <button
                onClick={() => setResetConfirmOpen(true)}
                className="focus-ring flex items-center gap-1.5 rounded-md border border-brand-red/40 px-3 py-1.5 text-xs font-semibold text-brand-red hover:bg-brand-red/10"
              >
                <RefreshCw size={13} /> Reset stream key
              </button>
            </div>
          </div>

          <div className="rounded-lg border border-surface-border bg-surface-panel p-5">
            <h2 className="mb-3 text-sm font-semibold text-ink">Where to paste it — {software === "obs" ? "OBS Studio" : "Streamlabs Desktop"}</h2>
            {software === "obs" ? (
              <ol className="ml-4 list-decimal space-y-1.5 text-sm text-ink-muted">
                <li>Settings → Stream → Service: Custom…</li>
                <li>Paste the Server URL above into &ldquo;Server&rdquo;</li>
                <li>Paste your stream key into &ldquo;Stream Key&rdquo;</li>
                <li>Click Apply, then OK</li>
              </ol>
            ) : (
              <ol className="ml-4 list-decimal space-y-1.5 text-sm text-ink-muted">
                <li>Settings → Stream → Streaming Platform: Custom Ingest</li>
                <li>Paste the Server URL into &ldquo;Stream URL&rdquo;</li>
                <li>Paste your stream key into &ldquo;Stream Key&rdquo;</li>
                <li>Click Done</li>
              </ol>
            )}
          </div>

          <button onClick={() => setStep(3)} className="focus-ring rounded-md bg-brand-magenta px-4 py-2 text-sm font-semibold text-white hover:bg-brand-magenta/90">
            Continue to recommended settings
          </button>
        </div>
      )}

      {step === 3 && (
        <div className="space-y-4">
          <div className="rounded-lg border border-surface-border bg-surface-panel p-5">
            <h2 className="mb-1 flex items-center gap-1.5 text-sm font-semibold text-ink">
              <Gauge size={15} /> What&apos;s your internet upload speed?
            </h2>
            <p className="mb-3 text-xs text-ink-faint">Run a speed test (e.g. fast.com) and enter the upload number in Mbps — settings below update automatically.</p>
            <div className="flex items-center gap-2">
              <input
                type="range"
                min={2}
                max={50}
                value={uploadMbps}
                onChange={(e) => setUploadMbps(Number(e.target.value))}
                className="w-full max-w-xs accent-brand-magenta"
              />
              <span className="w-20 shrink-0 text-sm font-semibold text-ink">{uploadMbps} Mbps</span>
            </div>
          </div>

          <div className="rounded-lg border border-surface-border bg-surface-panel p-5">
            <h2 className="mb-3 text-sm font-semibold text-ink">Recommended encoder settings for your connection</h2>
            <dl className="space-y-2 text-sm">
              <Row label="Video bitrate" value={`${bitrate.toLocaleString()} Kbps`} />
              <Row label="Resolution" value={profile.resolution} />
              <Row label="Frame rate" value={profile.fps} />
              <Row label="Audio bitrate" value="160 Kbps, 48 kHz" />
              <Row label="Keyframe interval" value="2 seconds" />
              <Row label="Encoder" value="Hardware (NVENC/QuickSync) preferred; x264 veryfast as fallback" />
            </dl>
            {uploadMbps < 5 && (
              <p className="mt-3 rounded-md border border-amber-400/30 bg-amber-400/[0.06] p-2.5 text-xs text-amber-400">
                Your upload speed is on the low side for 1080p — 720p30 will look sharper and drop far fewer frames than pushing 1080p over a
                slow connection.
              </p>
            )}
          </div>

          <button onClick={() => setStep(4)} className="focus-ring rounded-md bg-brand-magenta px-4 py-2 text-sm font-semibold text-white hover:bg-brand-magenta/90">
            Continue to test connection
          </button>
        </div>
      )}

      {step === 4 && (
        <div className="rounded-lg border border-surface-border bg-surface-panel p-5">
          <h2 className="mb-1 flex items-center gap-1.5 text-sm font-semibold text-ink">
            <Wrench size={15} /> Test your connection before going live
          </h2>
          <p className="mb-3 text-xs text-ink-faint">Start streaming in {software === "obs" ? "OBS" : "Streamlabs"} first, then run the test below.</p>
          <div className="flex flex-wrap items-center gap-3">
            <button onClick={runTest} disabled={testState === "testing"} className="focus-ring rounded-md bg-ink px-4 py-2 text-sm font-semibold text-surface hover:bg-ink/90 disabled:opacity-60">
              {testState === "testing" ? "Testing…" : "Test connection"}
            </button>
            <ConnectionStatus state={testState} />
          </div>

          {testState === "success" && (
            <div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">
              <HealthStat icon={Activity} label="Bitrate" value={`${bitrate.toLocaleString()} Kbps`} good />
              <HealthStat icon={Activity} label="Dropped frames" value="0.1%" good />
              <HealthStat icon={Activity} label="Latency" value="1.9s" good />
              <HealthStat icon={Activity} label="Connection health" value="Excellent" good />
            </div>
          )}

          {testState === "failed" && testError && (
            <div className="mt-4 rounded-md border border-brand-red/30 bg-brand-red/[0.06] p-4">
              <p className="flex items-center gap-1.5 text-sm font-semibold text-brand-red">
                <XCircle size={15} /> {testError.title}
              </p>
              <p className="mt-1.5 text-sm text-ink-muted">{testError.explanation}</p>
              <p className="mt-2 text-sm text-ink">
                <span className="font-medium text-brand-cyan">Try this: </span>
                {testError.fix}
              </p>
            </div>
          )}
        </div>
      )}

      <div className="rounded-lg border border-surface-border bg-surface-panel p-5">
        <h2 className="mb-3 text-sm font-semibold text-ink">How this works in production</h2>
        <ol className="ml-4 list-decimal space-y-1.5 text-sm text-ink-muted">
          <li>You receive a real RTMP or SRT ingest URL and a unique stream key from the connected video provider.</li>
          <li>You enter both into OBS or Streamlabs, exactly as on this page.</li>
          <li>OBS sends your broadcast over RTMP/SRT to that provider&apos;s ingest servers — never directly to thearcade.tv.</li>
          <li>The provider transcodes your stream into multiple quality renditions.</li>
          <li>Viewers receive the broadcast via HLS or low-latency HLS from the provider&apos;s CDN.</li>
          <li>The Arcade&apos;s player loads that HLS playback URL.</li>
          <li>Stream status and metadata (live/offline, viewer count) update via the provider&apos;s webhooks back to our API.</li>
        </ol>
      </div>

      <ConfirmDialog
        open={resetConfirmOpen}
        title="Reset your stream key?"
        description="Your current stream key will stop working immediately. Update OBS or Streamlabs with the new key before going live again."
        confirmLabel="Reset key"
        destructive
        onConfirm={() => {
          setStreamKey(randomKey());
          setVisible(true);
          setResetConfirmOpen(false);
          push({ kind: "success", title: "Stream key reset", description: "Update your encoder with the new key." });
        }}
        onCancel={() => setResetConfirmOpen(false)}
      />
    </div>
  );
}

function CopyField({ label, value, onCopy }: { label: string; value: string; onCopy: () => void }) {
  return (
    <div>
      <p className="mb-1 text-xs font-medium text-ink-muted">{label}</p>
      <div className="flex items-center gap-1.5">
        <code className="flex-1 truncate rounded-md border border-surface-border bg-surface-raised px-3 py-2 text-sm text-ink">{value}</code>
        <button onClick={onCopy} aria-label={`Copy ${label}`} className="focus-ring rounded-md border border-surface-border p-2 text-ink-muted hover:text-ink">
          <Copy size={15} />
        </button>
      </div>
    </div>
  );
}

function Row({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex justify-between gap-4">
      <dt className="text-ink-faint">{label}</dt>
      <dd className="text-right text-ink">{value}</dd>
    </div>
  );
}

function HealthStat({ icon: Icon, label, value, good }: { icon: typeof Activity; label: string; value: string; good?: boolean }) {
  return (
    <div className="rounded-md border border-surface-border bg-surface-raised p-3 text-center">
      <Icon size={14} className={`mx-auto ${good ? "text-brand-cyan" : "text-ink-muted"}`} />
      <p className={`mt-1 text-sm font-semibold ${good ? "text-brand-cyan" : "text-ink"}`}>{value}</p>
      <p className="text-[10px] text-ink-faint">{label}</p>
    </div>
  );
}

function ConnectionStatus({ state }: { state: TestState }) {
  if (state === "idle") return <span className="text-xs text-ink-faint">Not tested yet</span>;
  if (state === "testing")
    return (
      <span className="flex items-center gap-1.5 text-xs text-ink-muted">
        <Loader2 size={13} className="animate-spin" /> Contacting ingest server…
      </span>
    );
  if (state === "success")
    return (
      <span className="flex items-center gap-1.5 text-xs text-brand-cyan">
        <CheckCircle2 size={14} /> Connection healthy
      </span>
    );
  return (
    <span className="flex items-center gap-1.5 text-xs text-brand-red">
      <XCircle size={14} /> Connection failed — details below
    </span>
  );
}
