"use client";

import { useState } from "react";
import { CheckCircle2, Copy, Eye, EyeOff, Loader2, RefreshCw, XCircle } from "lucide-react";
import { ConfirmDialog } from "@/components/ui/ConfirmDialog";
import { useToast } from "@/components/ui/Toast";
import { useDemoSession } from "@/lib/demo-session";

const DEMO_INGEST_URL = "rtmp://ingest.demo.thearcade.tv/live";
const DEMO_STREAM_KEY_PREFIX = "arcade_demo_";

function randomKey() {
  return `${DEMO_STREAM_KEY_PREFIX}${Math.random().toString(36).slice(2, 10)}_${Math.random().toString(36).slice(2, 10)}`;
}

type TestState = "idle" | "testing" | "success" | "failed";

export default function StreamSetupPage() {
  const { creator } = useDemoSession();
  const { push } = useToast();
  const [streamKey, setStreamKey] = useState(() => randomKey());
  const [visible, setVisible] = useState(false);
  const [resetConfirmOpen, setResetConfirmOpen] = useState(false);
  const [testState, setTestState] = useState<TestState>("idle");

  if (!creator) return null;

  function copy(value: string, label: string) {
    navigator.clipboard
      .writeText(value)
      .then(() => push({ kind: "success", title: `${label} copied` }))
      .catch(() => push({ kind: "warning", title: "Couldn't copy", description: "Copy it manually instead." }));
  }

  function runTest() {
    setTestState("testing");
    window.setTimeout(() => {
      setTestState(Math.random() > 0.15 ? "success" : "failed");
    }, 1400);
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-xl font-semibold text-ink">Stream Setup</h1>
        <p className="mt-1 text-sm text-ink-muted">Connect OBS Studio or Streamlabs Desktop to broadcast on The Arcade.</p>
      </div>

      <div className="rounded-lg border border-amber-400/30 bg-amber-400/[0.06] p-4 text-sm text-ink-muted">
        These are demo credentials for this prototype — not a live ingest endpoint. In production, this screen is generated by a real video
        provider (see below), and OBS never talks to a normal webpage directly: it streams RTMP/SRT to that provider's ingest servers.
      </div>

      <div className="rounded-lg border border-surface-border bg-surface-panel p-5">
        <h2 className="mb-3 text-sm font-semibold text-ink">Ingest credentials</h2>
        <div className="space-y-3">
          <CopyField label="Server (RTMP URL)" value={DEMO_INGEST_URL} onCopy={() => copy(DEMO_INGEST_URL, "Server URL")} />
          <div>
            <p className="mb-1 text-xs font-medium text-ink-muted">Stream key</p>
            <div className="flex items-center gap-1.5">
              <code className="flex-1 truncate rounded-md border border-surface-border bg-surface-raised px-3 py-2 text-sm text-ink">
                {visible ? streamKey : "•".repeat(28)}
              </code>
              <button onClick={() => setVisible((v) => !v)} aria-label={visible ? "Hide stream key" : "Show stream key"} className="focus-ring rounded-md border border-surface-border p-2 text-ink-muted hover:text-ink">
                {visible ? <EyeOff size={15} /> : <Eye size={15} />}
              </button>
              <button onClick={() => copy(streamKey, "Stream key")} aria-label="Copy stream key" className="focus-ring rounded-md border border-surface-border p-2 text-ink-muted hover:text-ink">
                <Copy size={15} />
              </button>
            </div>
            <p className="mt-1 text-xs text-ink-faint">Never share your stream key — anyone with it can broadcast as you.</p>
          </div>
          <button
            onClick={() => setResetConfirmOpen(true)}
            className="focus-ring flex items-center gap-1.5 rounded-md border border-brand-red/40 px-3 py-1.5 text-xs font-semibold text-brand-red hover:bg-brand-red/10"
          >
            <RefreshCw size={13} /> Reset stream key
          </button>
        </div>

        <div className="mt-5 border-t border-surface-border pt-4">
          <div className="flex flex-wrap items-center gap-3">
            <button onClick={runTest} disabled={testState === "testing"} className="focus-ring rounded-md bg-ink px-4 py-2 text-sm font-semibold text-surface hover:bg-ink/90 disabled:opacity-60">
              {testState === "testing" ? "Testing…" : "Test connection"}
            </button>
            <ConnectionStatus state={testState} />
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
        <div className="rounded-lg border border-surface-border bg-surface-panel p-5">
          <h2 className="mb-3 text-sm font-semibold text-ink">Recommended settings</h2>
          <dl className="space-y-2 text-sm">
            <Row label="Video bitrate" value="6,000 Kbps (max 8,500)" />
            <Row label="Resolution" value="1920×1080" />
            <Row label="Frame rate" value="60 fps" />
            <Row label="Audio bitrate" value="160 Kbps, 48 kHz" />
            <Row label="Keyframe interval" value="2 seconds" />
            <Row label="Encoder" value="Hardware (NVENC/QuickSync) preferred; x264 veryfast as fallback" />
          </dl>
        </div>
        <div className="rounded-lg border border-surface-border bg-surface-panel p-5">
          <h2 className="mb-3 text-sm font-semibold text-ink">Setup instructions</h2>
          <div className="space-y-4 text-sm text-ink-muted">
            <div>
              <p className="font-medium text-ink">OBS Studio</p>
              <ol className="ml-4 list-decimal space-y-1 mt-1">
                <li>Settings → Stream → Service: Custom…</li>
                <li>Paste the Server URL above into &ldquo;Server&rdquo;</li>
                <li>Paste your stream key into &ldquo;Stream Key&rdquo;</li>
                <li>Apply, then click Start Streaming</li>
              </ol>
            </div>
            <div>
              <p className="font-medium text-ink">Streamlabs Desktop</p>
              <ol className="ml-4 list-decimal space-y-1 mt-1">
                <li>Settings → Stream → Streaming Platform: Custom Ingest</li>
                <li>Paste the Server URL and Stream Key above</li>
                <li>Done, then click Go Live</li>
              </ol>
            </div>
          </div>
        </div>
      </div>

      <div className="rounded-lg border border-surface-border bg-surface-panel p-5">
        <h2 className="mb-3 text-sm font-semibold text-ink">How this works in production</h2>
        <ol className="ml-4 list-decimal space-y-1.5 text-sm text-ink-muted">
          <li>You receive a real RTMP or SRT ingest URL and a unique stream key from the connected video provider.</li>
          <li>You enter both into OBS or Streamlabs, exactly as on this page.</li>
          <li>OBS sends your broadcast over RTMP/SRT to that provider's ingest servers — never directly to thearcade.tv.</li>
          <li>The provider transcodes your stream into multiple quality renditions.</li>
          <li>Viewers receive the broadcast via HLS or low-latency HLS from the provider's CDN.</li>
          <li>The Arcade's player loads that HLS playback URL.</li>
          <li>Stream status and metadata (live/offline, viewer count) update via the provider's webhooks back to our API.</li>
        </ol>
      </div>

      <ConfirmDialog
        open={resetConfirmOpen}
        title="Reset your stream key?"
        description="Your current stream key will stop working immediately. Update OBS or Streamlabs with the new key before going live again."
        confirmLabel="Reset key"
        destructive
        onConfirm={() => {
          setStreamKey(randomKey());
          setVisible(true);
          setResetConfirmOpen(false);
          push({ kind: "success", title: "Stream key reset", description: "Update your encoder with the new key." });
        }}
        onCancel={() => setResetConfirmOpen(false)}
      />
    </div>
  );
}

function CopyField({ label, value, onCopy }: { label: string; value: string; onCopy: () => void }) {
  return (
    <div>
      <p className="mb-1 text-xs font-medium text-ink-muted">{label}</p>
      <div className="flex items-center gap-1.5">
        <code className="flex-1 truncate rounded-md border border-surface-border bg-surface-raised px-3 py-2 text-sm text-ink">{value}</code>
        <button onClick={onCopy} aria-label={`Copy ${label}`} className="focus-ring rounded-md border border-surface-border p-2 text-ink-muted hover:text-ink">
          <Copy size={15} />
        </button>
      </div>
    </div>
  );
}

function Row({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex justify-between gap-4">
      <dt className="text-ink-faint">{label}</dt>
      <dd className="text-right text-ink">{value}</dd>
    </div>
  );
}

function ConnectionStatus({ state }: { state: TestState }) {
  if (state === "idle") return <span className="text-xs text-ink-faint">Not tested yet</span>;
  if (state === "testing")
    return (
      <span className="flex items-center gap-1.5 text-xs text-ink-muted">
        <Loader2 size={13} className="animate-spin" /> Contacting ingest server…
      </span>
    );
  if (state === "success")
    return (
      <span className="flex items-center gap-1.5 text-xs text-brand-cyan">
        <CheckCircle2 size={14} /> Connection healthy
      </span>
    );
  return (
    <span className="flex items-center gap-1.5 text-xs text-brand-red">
      <XCircle size={14} /> Couldn&apos;t reach ingest — check your key and network
    </span>
  );
}
